'use client';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import * as THREE from 'three';
import { useMemo, useRef } from 'react';
import type { MutableRefObject } from 'react';
import type { MotionState } from './story';
type Props = { motion: MutableRefObject<MotionState>; mobile: boolean; onReady: () => void; onFailure: () => void };
function Core({ motion }: { motion: MutableRefObject<MotionState> }) {
  const group = useRef<THREE.Group>(null); const shell = useRef<THREE.Mesh>(null);
  useFrame(({ camera, clock }) => { const m=motion.current; if(group.current){group.current.rotation.set(m.tilt+Math.sin(clock.elapsedTime*.17)*.025,m.rotation,m.rotation*.18);group.current.scale.setScalar(.9+m.expansion*.22);group.current.position.x=-m.targetX*.12;} if(shell.current&&shell.current.material instanceof THREE.MeshStandardMaterial){shell.current.material.opacity=.06+m.seal*.1;shell.current.material.emissiveIntensity=.12+m.light*.1;} camera.position.lerp(new THREE.Vector3(m.cameraX,m.cameraY,m.cameraZ),.045);camera.lookAt(new THREE.Vector3(0,m.targetX*-.08,0)); });
  return <group ref={group}><mesh ref={shell} scale={[2.5,2.5,2.5]}><icosahedronGeometry args={[1,2]}/><meshStandardMaterial color="#c7d2b2" emissive="#a4b57c" transparent opacity={.06} wireframe metalness={.8} roughness={.25}/></mesh>{Array.from({length:9},(_,i)=><mesh key={i} position={[0,(i-4)*.22,0]} rotation={[0,i*.18,i*.07]} scale={[1+i*.025,1,1+i*.025]}><boxGeometry args={[1.62,.075,1.62]}/><meshStandardMaterial color={i===4?'#dbe7c5':'#879294'} emissive={i===4?'#aabf79':'#1c2327'} emissiveIntensity={i===4?.55:.08} transparent opacity={.2+(4-Math.abs(i-4))*.08} metalness={.9} roughness={.26}/></mesh>)}<mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[1.75,.012,8,96]}/><meshBasicMaterial color="#d7e8a8" transparent opacity={.32}/></mesh></group>;
}
function ServiceField({motion,mobile}:{motion:MutableRefObject<MotionState>;mobile:boolean}){const group=useRef<THREE.Group>(null);const nodes=useMemo(()=>Array.from({length:mobile?6:12},(_,i)=>{const angle=i/(mobile?6:12)*Math.PI*2;return{angle,radius:3.2+(i%3)*.8,y:(i%4-1.5)*.55};}),[mobile]);useFrame(()=>{if(!group.current)return;const amount=motion.current.nodes;group.current.children.forEach((child,i)=>{const n=nodes[i];child.visible=amount>.05;child.position.set(Math.cos(n.angle)*n.radius*amount,n.y*amount,Math.sin(n.angle)*n.radius*amount);child.scale.setScalar(.55+motion.current.selection*(i===1?.32:0));});});return <group ref={group}>{nodes.map((_,i)=><mesh key={i}><octahedronGeometry args={[.13,0]}/><meshStandardMaterial color={i===1?'#d7e8a8':'#8c9798'} emissive={i===1?'#819a4b':'#303b3d'} emissiveIntensity={.55} metalness={.8} roughness={.35}/></mesh>)}</group>}
function Flow({motion}:{motion:MutableRefObject<MotionState>}){const group=useRef<THREE.Group>(null);useFrame(({clock})=>{if(!group.current)return;const amount=motion.current.flow;group.current.visible=amount>.04;group.current.scale.setScalar(.7+amount*.3);group.current.rotation.z=Math.sin(clock.elapsedTime*.24)*.08;});return <group ref={group}><mesh rotation={[0,Math.PI/2,0]} position={[2.45,0,0]}><cylinderGeometry args={[.018,.018,4.8,8]}/><meshBasicMaterial color="#d7e8a8" transparent opacity={.65}/></mesh>{[-1,1].map(side=><mesh key={side} position={[side*1.7,0,0]} rotation={[0,0,side*Math.PI/2]}><coneGeometry args={[.1,.34,4]}/><meshBasicMaterial color="#d7e8a8" transparent opacity={.75}/></mesh>)}</group>}
function MemoryField({motion,mobile}:{motion:MutableRefObject<MotionState>;mobile:boolean}){const group=useRef<THREE.Group>(null);const rows=mobile?3:5;useFrame(()=>{if(!group.current)return;const amount=motion.current.memory;group.current.visible=amount>.04;group.current.position.z=-1.5-amount*1.2;group.current.scale.setScalar(.72+amount*.28);});return <group ref={group}>{Array.from({length:rows},(_,row)=><group key={row} position={[0,(row-(rows-1)/2)*.56,0]}>{Array.from({length:mobile?7:11},(_,i)=><mesh key={i} position={[(i-5)*.38,0,Math.sin(i*1.7+row)*.15]}><boxGeometry args={[.23,.018,.018]}/><meshBasicMaterial color={row===2?'#d7e8a8':'#879294'} transparent opacity={.18+motion.current.memory*.4}/></mesh>)}</group>)}</group>}
function World({motion,mobile}:{motion:MutableRefObject<MotionState>;mobile:boolean}){const{gl}=useThree();useMemo(()=>{gl.setPixelRatio(Math.min(window.devicePixelRatio,mobile?1.25:1.65));},[gl,mobile]);return <><color attach="background" args={['#090b0c']}/><fog attach="fog" args={['#090b0c',7,20]}/><ambientLight intensity={.16} color="#c7d2cf"/><pointLight position={[2,3,4]} intensity={1.2} color="#d7e8a8" distance={9}/><pointLight position={[-5,-2,2]} intensity={.55} color="#82949a" distance={10}/><Core motion={motion}/><ServiceField motion={motion} mobile={mobile}/><Flow motion={motion}/><MemoryField motion={motion} mobile={mobile}/><gridHelper args={[18,mobile?10:18,'#1f292b','#111719']} position={[0,-2.45,0]}/></>}
export default function Scene({motion,mobile,onReady,onFailure}:Props){return <Canvas camera={{position:[5.8,3.6,10],fov:36,near:.1,far:40}} dpr={[1,mobile?1.25:1.65]} gl={{antialias:true,alpha:false,powerPreference:'high-performance'}} onCreated={()=>onReady()} onError={()=>onFailure()} fallback={null}><World motion={motion} mobile={mobile}/></Canvas>}
